language: rust
rust:
- stable
cache: cargo
sudo: required
dist: trusty
env:
  global:
  - NIGHTLY_RUST=nightly-2017-05-10
  - CLIPPY_VERS=0.0.131
  - RUSTFMT_VERS=0.9.0
  - secure: K5mZuLSnf9fYdGV0LjiMHKExcO+E9wi/LjxHZKKjaj+/pghYo2fz1/YBxNKAVl7DLWW1iLDEIRKj6DkciBVNnzUbpvLnuzizitdUeVKzSBVxDpOIB6h94K1QR2MUSUx7Xi84s93xBRpJljXo8pXFPLvhPKjHLv0fAHGooq2KwPPfCgWH5ofTRKNkVnyR8tscfGwh1AiQd8+OcJow3lnfXMnuex0kaAX6ziFQfg79nUojpv5DKmMBHh88ZH3TIHW2d4aa2Z/4ZoGfS3rP/LR70yPUZKfGlRmHo0fImam/fRouQJX0Yde7+dtt3sF34ZGwZOXHj5X/OUWPKkCvk6xuwb1qOugpFnr5N31ZoqYGCV8TfvtX+bCOsoUJU0tY7Zj4jRugG9c3IB+98Pr/ECH2Lp2G1ezYniDjzbV8k3rwMR5spMhkdEJdjmhrBuBKNiC+yJOyo5SSonDcf8y7w9DcwtvWUi2AMcmsp4SDSccFP9amOOvT/AW1wor+QEl+PdM14DB7IIVs2wdh23KrVKsZZcq0PR459Tb7YMeZJWslcZp/KGbamHnOs0fSt5ek5ey/zv2G4CdxEvG2naQJEqI7MtvDtHo0ttyrDDG3vb8cCJbEvi3CYI8aktIat4pSd9cNP8snE7eIaWcHUKYJDuPujQwBuHdNdqVWlAqwRnut4NQ=
before_install:
- rustfmt --version | grep $RUSTFMT_VERS || cargo install rustfmt --force --vers $RUSTFMT_VERS
- rustup toolchain install $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy --version | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST
  install clippy --force --vers $CLIPPY_VERS
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-get -qq update
install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev
script:
- cargo fmt -- --write-mode=diff
- cargo +$NIGHTLY_RUST clippy -- -D warnings
- cd ..
- cargo test
