language: rust
rust:
  - stable
cache: cargo
sudo: required
dist: trusty
env:
  global:
  - NIGHTLY_RUST=nightly-2017-05-10
  - CLIPPY_VERS=0.0.131
  - RUSTFMT_VERS=0.9.0
  - secure: K5mZuLSnf9fYdGV0LjiMHKExcO+E9wi/LjxHZKKjaj+/pghYo2fz1/YBxNKAVl7DLWW1iLDEIRKj6DkciBVNnzUbpvLnuzizitdUeVKzSBVxDpOIB6h94K1QR2MUSUx7Xi84s93xBRpJljXo8pXFPLvhPKjHLv0fAHGooq2KwPPfCgWH5ofTRKNkVnyR8tscfGwh1AiQd8+OcJow3lnfXMnuex0kaAX6ziFQfg79nUojpv5DKmMBHh88ZH3TIHW2d4aa2Z/4ZoGfS3rP/LR70yPUZKfGlRmHo0fImam/fRouQJX0Yde7+dtt3sF34ZGwZOXHj5X/OUWPKkCvk6xuwb1qOugpFnr5N31ZoqYGCV8TfvtX+bCOsoUJU0tY7Zj4jRugG9c3IB+98Pr/ECH2Lp2G1ezYniDjzbV8k3rwMR5spMhkdEJdjmhrBuBKNiC+yJOyo5SSonDcf8y7w9DcwtvWUi2AMcmsp4SDSccFP9amOOvT/AW1wor+QEl+PdM14DB7IIVs2wdh23KrVKsZZcq0PR459Tb7YMeZJWslcZp/KGbamHnOs0fSt5ek5ey/zv2G4CdxEvG2naQJEqI7MtvDtHo0ttyrDDG3vb8cCJbEvi3CYI8aktIat4pSd9cNP8snE7eIaWcHUKYJDuPujQwBuHdNdqVWlAqwRnut4NQ=
before_install:
- rustfmt --version | grep $RUSTFMT_VERS || cargo install rustfmt --force --vers $RUSTFMT_VERS
- rustup toolchain install $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy --version | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST
  install clippy --force --vers $CLIPPY_VERS
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-get -qq update
install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev
script:
- cargo fmt -- --write-mode=diff
- cargo +$NIGHTLY_RUST clippy -- -D warnings
- cargo test
notifications:
  slack:
    secure: SL00WFBrZYB5qVhnw3PEUhLexyP40klqmbultgrN8Yv+0XPi49hSoqDxndTw7+4bJqGyNvz18C0Um4sSYiSvSzqUYrptSfntW4TSt5ldVHcwTOd+Yogvz7ZrYqG5AgVlvLjGZgsod50HeHtYhfw7Pnh4NJoP700kPiz9Pk9ebXqLOmp8z4o3PQeSQr8RZugp47XeltRdPGgwM/RV7IoDmrV4UXkcrBHPMiSdpULvhC6IKfRTMsaoAs9ZJtFTB434s0rDj/bubq7N8o0CmqBmjmzQLoRMptYSC3TQxPs3uvvQeVt1s/s2HKLV7oa9qxwuN06mqrjvoUiyybKpVDV2svLMdBTxlLZ0onvHGw96Ecr19ZtADSoKCZanydkTBSLGmiyjpMwNfTz1++SvS0SQtPzabOECAGpG2/T4rNVIqhTXjuVafLIwDxQEojaGQ3qL6gJ967hQn3gayldEDdK6qeJrowp0PQG8CamBNwIU29gQelddOvL8aM+Me1aqZgWWHasxRZ56KYmx5+/EsnJf8Kux3Wa2NYRgBYyvIdAd4WG+SpiSYxGfxAOPlSUrM9mpzN7sn8MAPixi03mIJ/3TFXmFXB/tl9tMmoD81um0YtWjoCJue9+WSkmtRXakN8Z71VM7R2AI9WBJwYl02p0IdS3oXFxQmyJ/wplBSp5rVVM=
