[package]
name = "cryptocurrency"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
repository = "https://github.com/exonum/cryptocurrency"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
# TODO Change to version from crates (when MemoryDB fixes will be released)
exonum = { git = "https://github.com/exonum/exonum", rev = "64518cec0b091d2eeca6c62356b78dc37d5942ee" }
iron = "0.5.1"
bodyparser = "0.7.0"
params = "0.6.0"
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
